/// Flutter icons InstagramIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InstagramIcons
///      fonts:
///       - asset: fonts/InstagramIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class InstagramIcons {
  InstagramIcons._();

  static const _kFontFam = 'InstagramIcons';
  static const String? _kFontPkg = null;

  static const IconData save = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direct = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram_reel = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
